# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=500)),
                ('week', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('relation', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.CharField(max_length=500)),
                ('commodity', models.CharField(choices=[('produt', 'product'), ('membership', 'membership'), ('test', 'test')], max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('bcolor', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RankRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skf.Rank')),
            ],
        ),
        migrations.CreateModel(
            name='RankRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skf.Rank')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_num', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='rankrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skf.Student'),
        ),
        migrations.AddField(
            model_name='rank',
            name='student',
            field=models.ManyToManyField(through='skf.RankRecord', to='skf.Student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skf.Student'),
        ),
        migrations.AddField(
            model_name='parents',
            name='students',
            field=models.ManyToManyField(to='skf.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='skf.Student'),
        ),
    ]
