# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parents',
            new_name='Parent',
        ),
    ]
