# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0002_auto_20170407_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='week',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=500),
        ),
    ]
