# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0004_payment_sdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sdate',
            field=models.DateField(default='django.utils.timezone.now'),
        ),
    ]
