# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0006_auto_20170408_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='edate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rankrecord',
            name='rdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='djs',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sdate',
            field=models.DateField(auto_now=True),
        ),
    ]
