# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 02:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0008_auto_20170408_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sdate',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 2, 32, 23, 329653)),
        ),
    ]
