# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0011_auto_20170408_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sdate',
            field=models.DateField(blank=True),
        ),
    ]
