# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0013_auto_20170408_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(choices=[('8:00 am', '8:00 am'), ('9:00 am', '9:00 am'), ('10:00 am', '10:00 am'), ('11:00 am', '11:00 am'), ('12:00 pm', '12:00 pm'), ('1:00 pm', '1:00 pm'), ('2:00 pm', '2:00 pm'), ('3:00 pm', '3:00 pm'), ('4:00 pm', '4:00 pm'), ('5:00 pm', '5:00 pm'), ('6:00 pm', '6:00 pm'), ('7:00 pm', '7:00 pm'), ('8:00 pm', '8:00 pm'), ('9:00 pm', '9:00 pm')], default='8:00 am', max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='commodity',
            field=models.CharField(choices=[('produt', 'Product'), ('membership', 'Membership'), ('test', 'Test')], max_length=500),
        ),
    ]
