# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skf', '0015_auto_20170408_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='commodity',
            field=models.CharField(choices=[('Produt', 'Product'), ('Membership', 'Membership'), ('Test', 'Test')], default='Product', max_length=500),
        ),
    ]
